# Generated by Django 4.0.4 on 2022-04-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifToken',
            new_name='SpotifyToken',
        ),
    ]
